### ISSUE TITLE
relace variable

### ISSUE THREAD

**Issue by bagart** [kefzce/CryptoCurrencyExchangesTrader#25]
[ProviderBuilderTest.php#L65](https://github.com/kefzce/CryptoCurrencyExchangesTrader/blob/50b9a81bdbda60aea3606ad9fde5ebe6f4d15b8f/tests/Provider/ProviderBuilderTest.php#L65)

replace variable will make some tests impossible in the feature

**Comment by kefzce** [comment]
> [ProviderBuilderTest.php#L65](https://github.com/kefzce/CryptoCurrencyExchangesTrader/blob/50b9a81bdbda60aea3606ad9fde5ebe6f4d15b8f/tests/Provider/ProviderBuilderTest.php#L65)
> 
> replace variable will make some tests impossible in the feature

??

**Comment by bagart** [comment]
Replace variable with change type is a bad practics. For example, in this test replace provider name to provider instance make impossibleChrk provider  compare instance with

**Comment by kefzce** [comment]
> Replace variable with change type is a bad practics. For example, in this test replace provider name to provider instance make impossibleChrk provider compare instance with
https://github.com/kefzce/CryptoCurrencyExchangesTrader/blob/9ab7b5c007fc0a14ad6cacd6e02f26d4e5663bd1/src/CryptoCurrencyExchanges/Provider/ProviderBuilder.php#L30-L41

https://github.com/kefzce/CryptoCurrencyExchangesTrader/blob/9ab7b5c007fc0a14ad6cacd6e02f26d4e5663bd1/src/CryptoCurrencyExchanges/Provider/BaseProvider.php#L9-L22

Builder use Dependency Injection Container which expect FQCN (string) to create an instance,by the way this behavior is used quite often in this project or even symfony/laravel do it.

You can send Pull Request so that I could look more objectively at your proposal
